spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/rinha
    username: rinha
    password: rinha
    pool:
      max-size: 100
      initial-size: 50
      max-idle-time: 10m

## ATENCAO DESATIVA LOG DE SQL
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

server:
  port: 9999
