version: '3.7'

services:
  db-rinha:
    image: mariadb:11.1
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: rinha
        MYSQL_USER: rinha
        MYSQL_PASSWORD: rinha